// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teste.Superdigital.Infraestructure.Data.Context;

namespace Teste.Superdigital.Infraestructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teste.Superdigital.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<int>("ContaCorrenteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Criacao");

                    b.Property<int>("Numero");

                    b.Property<double>("Saldo");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("ContaCorrenteId");

                    b.ToTable("ContasCorrentes");
                });
#pragma warning restore 612, 618
        }
    }
}
